import numpy as np

DEGREE_TO_RADIAN = np.pi/180

MILLISECOND_TO_SECOND = 1e-3

MILLIMETER_TO_METER = 1e-3
MICROMETER_TO_METER = 1e-6

GRAMM_TO_KILOGRAMM = 1e-3

MEGAPASCAL_TO_PASCAL = 1e6
GIGAPASCAL_TO_PASCAL = 1e9

RPM_TO_RADPSEC = 2*np.pi/60
RPM_TO_DEGPSEC = 360/60

KILONEWTON_TO_NEWTON = 1e3 